### ISSUE TITLE
Released without generate dist files?

### ISSUE THREAD

**Issue by andersonba** [ariesjia/riot-testing-library#2]
```
Error: Cannot find module 'riot-testing-library'
```

Where's the `dist` folder?

```bash
♦ cat node_modules/riot-testing-library/package.json |jq .main
"dist/index.js"

♦ ls node_modules/riot-testing-library/dist
ls: cannot access 'node_modules/riot-testing-library/dist': No such file or directory

♦ ls node_modules/riot-testing-library
LICENSE  README.md  dont-cleanup-after-each.js  jest.config.js  package.json  tsconfig.json
```

How did I install?

```
yarn add -D riot-testing-library
```

**Comment by ariesjia** [comment]
Fixed，It have a major issue in Github Action.  https://github.com/ariesjia/riot-testing-library/commit/77b87bb418760329cd19cb7c7e1b4e540288f202
It didn't  run `build` correctly. Now it's works. 
I forget should write `run` when using npm. 😂
You can use yarn or npm to install it. 
Thanks.·
